import { Prospect, RevenueDataPoint, DashboardStats } from "@/types/prospect";
import { subDays, format } from "date-fns";

export const MOCK_PROSPECTS: Prospect[] = [
  {
    id: "1",
    siret: "98765432100012",
    siren: "987654321",
    companyName: "DIGITAL VENTURES SAS",
    directorName: "Alexandre Martin",
    nafCode: "6201Z",
    nafLabel: "Programmation informatique",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    address: "12 Rue de la Paix",
    city: "Paris",
    postalCode: "75002",
    email: "a.martin@digitalventures.fr",
    status: "identified",
    aiInsight: "Startup tech récente — fort besoin en comptabilité SaaS et gestion des notes de frais.",
    accountingNeed: "Mise en place d'une comptabilité analytique + gestion TVA intracommunautaire",
    estimatedRevenue: 1800,
    scrapedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "2",
    siret: "12345678900034",
    siren: "123456789",
    companyName: "CONSEIL & STRATÉGIE EURL",
    directorName: "Sophie Dubois",
    nafCode: "7022Z",
    nafLabel: "Conseil pour les affaires",
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    address: "8 Avenue Montaigne",
    city: "Lyon",
    postalCode: "69006",
    status: "email_sent",
    aiInsight: "Cabinet de conseil indépendant — nécessite suivi des honoraires et facturation clients.",
    accountingNeed: "Tenue comptable mensuelle + déclarations TVA + liasse fiscale",
    estimatedRevenue: 2400,
    scrapedAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "3",
    siret: "55544433300021",
    siren: "555444333",
    companyName: "MAISON LEFORT IMMOBILIER",
    directorName: "Pierre Lefort",
    nafCode: "6831Z",
    nafLabel: "Agences immobilières",
    createdAt: new Date(Date.now() - 14400000).toISOString(),
    address: "45 Rue du Commerce",
    city: "Bordeaux",
    postalCode: "33000",
    email: "p.lefort@maisonlefort.fr",
    status: "payment_received",
    aiInsight: "Agence immobilière — gestion des commissions, SCI et comptabilité de promotion.",
    accountingNeed: "Comptabilité agence + gestion SCI + optimisation fiscale",
    estimatedRevenue: 3200,
    invoiceGenerated: true,
    scrapedAt: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: "4",
    siret: "77788899900056",
    siren: "778889999",
    companyName: "FLOW CREATION SARL",
    directorName: "Camille Nguyen",
    nafCode: "7311Z",
    nafLabel: "Agences de publicité",
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    address: "23 Rue des Entrepreneurs",
    city: "Nantes",
    postalCode: "44000",
    status: "identified",
    aiInsight: "Agence créative — besoin urgent en structuration comptable et suivi des projets clients.",
    accountingNeed: "Comptabilité par projets + facturation récurrente + gestion des freelances",
    estimatedRevenue: 1500,
    scrapedAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: "5",
    siret: "33322211100078",
    siren: "333222111",
    companyName: "TECHLAB INNOVATIONS",
    directorName: "Romain Petit",
    nafCode: "7219Z",
    nafLabel: "Recherche-développement",
    createdAt: new Date(Date.now() - 900000).toISOString(),
    address: "7 Allée de l'Innovation",
    city: "Toulouse",
    postalCode: "31000",
    status: "identified",
    aiInsight: "Deep tech en R&D — éligible CIR/JEI, besoin d'accompagnement comptable spécialisé.",
    accountingNeed: "Comptabilité R&D + dossier CIR + suivi des aides publiques",
    estimatedRevenue: 4500,
    scrapedAt: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: "6",
    siret: "44455566600089",
    siren: "444555666",
    companyName: "VERT & CO BIO",
    directorName: "Emma Rousseau",
    nafCode: "4711B",
    nafLabel: "Commerce bio et alimentaire",
    createdAt: new Date(Date.now() - 28800000).toISOString(),
    address: "3 Place du Marché",
    city: "Montpellier",
    postalCode: "34000",
    status: "email_sent",
    aiInsight: "Commerce bio en croissance — gestion des stocks, fournisseurs et TVA alimentaire réduite.",
    accountingNeed: "Comptabilité commerce + gestion taux TVA multiples + bilan annuel",
    estimatedRevenue: 1200,
    scrapedAt: new Date(Date.now() - 28800000).toISOString(),
  },
];

export function generateRevenueData(): RevenueDataPoint[] {
  return Array.from({ length: 30 }, (_, i) => {
    const date = subDays(new Date(), 29 - i);
    const baseRevenue = 800 + Math.random() * 2400;
    const isWeekend = date.getDay() === 0 || date.getDay() === 6;
    return {
      date: format(date, "dd/MM"),
      revenue: isWeekend ? Math.floor(baseRevenue * 0.3) : Math.floor(baseRevenue),
      prospects: Math.floor(Math.random() * 15) + 2,
      conversions: Math.floor(Math.random() * 4),
    };
  });
}

export const DASHBOARD_STATS: DashboardStats = {
  totalProspects: 847,
  emailsSent: 312,
  paymentsReceived: 89,
  conversionRate: 28.5,
  dailyRevenue: 4200,
  totalRevenue: 127500,
  newToday: 23,
};
